image: thinkr/rfull:latest
test:
  script:
  - R CMD build . --no-build-vignettes --no-manual
  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
  - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual
  - R CMD INSTALL "${PKG_FILE_NAME}"
  - R -e 'devtools::test()'





